- defaults:
    name: jenkins-jobs
    project-type: freestyle
    properties:
      - delivery-pipeline:
          stage: '{pipeline-stage}'
    scm:
      - git:
          name: demo-coreos-jenkins
          url: "https://github.com/wouterla/pipeline-demo-swarm.git"
          skip-tag: true
          wipe-workspace: false
          branches:
            - master
    wrappers:
      - ansicolor

- job:
    name: 'jenkins-job-builder-create-docker-image'
    defaults: jenkins-jobs
    builders:
      - shell: |
          #!/bin/bash
          set +x
          export DOCKER_HOST=${{DOCKER_HOST}}

          echo "Clean..."
          rm -rf build && mkdir build

          echo "generating files with ansible"
          ansible-playbook -i hosts_local site_jenkins_jobs_docker.yml

          echo "Copying docker files"
          cp docker/jenkins-job-builder/* build/

          echo "Running docker"
          cd build
          docker build -t wouterla/docker-jenkins-job-builder .

          echo "Pushing docker image to repository"
          #docker push wouterla/docker-jenkins-job-builder
    publishers:
      - trigger-with-params:
          next-job: 'jenkins-job-builder-deploy'

- job:
    name: 'jenkins-job-builder-deploy'
    defaults: jenkins-jobs
    wrappers:
      inject:
        properties-content: |
          DOCKER_HOST=${{DOCKER_HOST}}
          ENV=build
    builders:
      - shell: |
          #!/bin/bash
          set -x
          set +e
          docker run --net=${ENV} --name=jenkins-job-builder -it wouterla/docker-jenkins-job-builder
    triggers:
    publishers:
      - trigger-with-params:
          next-job: 'done'

- project:
    name: 'jenkins-job-builder'
    jobs:
      - '{name}-start':
          next-job: 'jenkins-job-builder-create-docker-image'
          gitrepo: 'pipeline-demo-swarm'
          pipeline-stage: 'build'
          branch: 'master'
      - 'jenkins-job-builder-create-docker-image':
          pipeline-stage: 'build'
      - 'jenkins-job-builder-deploy':
          pipeline-stage: 'production'
      - done:
          pipeline-stage: 'production'
